/// Flutter icons NavbarIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavbarIcons
///      fonts:
///       - asset: fonts/NavbarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NavbarIcons {
  NavbarIcons._();

  static const _kFontFam = 'NavbarIcons';
  static const String? _kFontPkg = null;

  static const IconData cart = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
